### ISSUE TITLE
Openapi.json not fetchable from /api/rbac/v1/openapi.json

### ISSUE THREAD

**Issue by lcouzens** [RedHatInsights/insights-rbac#103]
**Describe the bug**
Openapi.json not fetchable from /api/rbac/v1/openapi.json

**To Reproduce**
1. Go to /api/rbac/v1/openapi.json
2. Nothing loads

**Expected behavior**
Should be able to fetch the openapi.json from here.

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 6e05d8cb2ac3f6fa26fe19a1e8797a73bb312e91

**Additional context**
I was failing to fetch this from CI/QA and PROD however was able to fetch it from /api/rbac/v1/openapi.json.gz but it required authentication. It should work from the standard endpoint and I believe shouldn't require authentication.

**Comment by chambridge** [comment]
@lcouzens This is now available for testing in *CI* from PR: #105
Please close when verified.

**Comment by lcouzens** [comment]
Verified!
