### ISSUE TITLE
An internal flag for roles and policies

### ISSUE THREAD

**Issue by bzwei** [RedHatInsights/insights-rbac#113]
The RBAC UI allow admins to create policies and view roles. Our apps also create policies and roles, often because roles with ACLs for selected entities are needed to be created on the fly. They are not directly created by users (admins) therefore should not be visible on UI.

We propose to have an internal flag when creating roles and policies. The default value can be false. UI can then list those having the internal flag to be false. This flag needs to be in the listing option too.

**Comment by mkanoor** [comment]
@bzwei since we have moved the ACL's roles into our apps do we need this anymore?
