### ISSUE TITLE
Test Case for orphaned policy

### ISSUE THREAD

**Issue by chambridge** [RedHatInsights/insights-rbac#17]
**Describe the bug**
Create a test case that covers the potential for orphaned policy.

Policies could be orphaned in two ways:
- Group is deleted
- Policy contained only one role and that role is deleted.

In both of the above cases the associated policy should be removed.

**Comment by mkanoor** [comment]
data
```
{:name=>"f6adb9d9-6a6c-46fb-a59c-03cd38f4099b-Sharing", :description=>"Shared Policy", :group=>"{:uuid=>\"50030a7f-5684-4ff5-bcc6-a313ad134d25\", :name=>\"Catalog Operators\", :description=>\"Catalog Operators can order a portfolio similar to the Catalog Users\", :principals=>[]}", :roles=>[], :uuid=>"203b5186-27d4-4898-acdb-c3287fcebf4f"}
```
