### ISSUE TITLE
Filter objects by name in list_* calls

### ISSUE THREAD

**Issue by mkanoor** [RedHatInsights/insights-rbac#40]
## User Story
The user making the API call would want to fetch objects where the name matches a sub string
Without this API the user would have to fetch all the objects and then filter out the ones he needs. By pushing the filter logic to the server side we can limit the number of objects being exchanged.
## Impacts
API, UI, Docs

## Assumptions
- Supports simple regular expression (e.g. name = test_1*)
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/roles/ |
 | **Body** |  |
 | **Response** | |

## Acceptance Criteria

- [ ]
- [ ]

**Comment by chambridge** [comment]
https://github.com/RedHatInsights/insights-rbac/pull/42
